baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MyDecisive Documentation'

# theme stuff here

# theme = 
theme = 

[services]
  [services.googleAnalytics]
    ID = 'G-3LC2SJ2HZN'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  # BookTheme = 'dark'
  
  themeVariant = "relearn-dark"
  linkTitle = " " # Sets text at top of sidebar, replace with logo, has space to prevent default behavior
  landingPageName = '<i class="fa-fw fas fa-home"></i> Documentation' # text with home button
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = true

# theme = 'ananke' this is a basic/default but not really for docs
# theme = 'docsy' <-- this looks great on paper but very complicated error-prone setup

# sidebar menu
collapsibleMenu = true

[menu]
  [[menu.before]]
    name = 'Home'
    pageRef = '/'
    weight = 1

[[menu.shortcuts]]
  name = "â† MyDecisive Webpage"
  url = "https://www.mydecisive.ai/"
  weight = 2



# experimental to see if images will render correctly...
[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true  # enable embedded image render hook
      [markup.goldmark.renderHooks.link]
        enableDefault = true
    [markup.goldmark.renderer]
      unsafe= true
